# Build Stage
FROM node:lts-bookworm-slim  AS BUILD_IMAGE
WORKDIR /app
COPY package*.json ./
RUN npm ci --legacy-peer-deps
COPY . .
RUN npm run build


# Production Stage
FROM node:lts-bookworm-slim  AS PRODUCTION_STAGE
WORKDIR /app
COPY --from=BUILD_IMAGE /app ./
ENV NODE_ENV=production
EXPOSE 3000
CMD ["npm", "start"]