
version: '3.8'
services:
  web:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: npm run start
    ports:
      - "8009:3000"
    env_file:
      - .env.local