import type { Metadata } from 'next'
import 'overlayscrollbars/overlayscrollbars.css'
import '@/app/codeEditor.css'

export const metadata: Metadata = {
	title: 'Code Editor',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<div>{children}</div>
	)
}
