import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { NextAuthProvider } from '../contexts/NextAuth/Provider'
import { ThemeProvider } from '../contexts/Theme/Provider'
import NextTopLoader from 'nextjs-toploader'
import { OptionProvider } from '../contexts/Option/Provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en" suppressHydrationWarning={true}>
			<body className={inter.className} suppressHydrationWarning={true}>
				<NextTopLoader />

				<NextAuthProvider>
					<ThemeProvider>
						<OptionProvider>{children}</OptionProvider>
					</ThemeProvider>
				</NextAuthProvider>
			</body>
		</html>
	)
}
